"use server";

import { z } from "zod";

import { prisma } from "@/lib/prisma";
import { CategoryType } from "@/generated/client";
import { getUserData } from "@/lib/data";
import { resetUserToDefaults } from "@/lib/user-seed";
import type { FinanceSnapshot } from "@/store/useFinanceStore";
import { requireUserId } from "./_session";

// ─────────────────────────────────────────────────────────────────────────────
// Backup / Restore / Reset (step 5)
//
// Export  — serialises EVERY entity of the CURRENT user (incomes, expenses,
//           goals, categories, prefs) into one JSON file. The client turns it
//           into a downloadable .json (and a PDF report).
// Restore — validates an uploaded backup (zod) and REPLACES the current user's
//           data in a single Prisma transaction. Strictly userId-scoped, so it
//           can never read or write another user's rows. Incoming ids are
//           ignored (fresh cuid()s are generated) to avoid cross-DB collisions.
// Reset   — wipes the user's data and restores default categories + prefs.
// ─────────────────────────────────────────────────────────────────────────────

export type BackupFile = {
  app: "MyFinance";
  version: number;
  exportedAt: string;
  data: FinanceSnapshot;
};

export async function exportUserData(): Promise<BackupFile> {
  await requireUserId(); // getUserData re-checks too; explicit for clarity.
  const data = await getUserData();
  return {
    app: "MyFinance",
    version: 1,
    exportedAt: new Date().toISOString(),
    data,
  };
}

// ── Restore validation ────────────────────────────────────────────────────────

const dateString = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Invalid date");

const categorySchema = z.object({
  name: z.string().trim().min(1).max(60),
  icon: z.string().trim().min(1).max(60),
  type: z.enum(["income", "expense"]),
  isDefault: z.boolean().optional(),
});

const incomeSchema = z.object({
  date: dateString,
  source: z.string().trim().min(1).max(200),
  category: z.string().trim().min(1).max(100),
  amount: z.number().finite().nonnegative(),
  notes: z.string().trim().max(1000).nullish(),
});

const expenseSchema = z.object({
  date: dateString,
  description: z.string().trim().min(1).max(200),
  category: z.string().trim().min(1).max(100),
  amount: z.number().finite().nonnegative(),
  status: z.enum(["Paid", "Pending"]),
});

const goalSchema = z.object({
  name: z.string().trim().min(1).max(200),
  icon: z.string().trim().min(1).max(60),
  saved: z.number().finite().nonnegative(),
  target: z.number().finite().positive(),
  targetDate: dateString,
});

const prefsSchema = z
  .object({
    currency: z.string().trim().min(1).max(8),
    language: z.string().trim().min(2).max(8),
    theme: z.enum(["light", "dark", "system"]),
    displayName: z.string().trim().max(120),
    monthlyBudget: z.number().finite().nonnegative(),
  })
  .partial();

const backupData = z.object({
  incomes: z.array(incomeSchema).default([]),
  expenses: z.array(expenseSchema).default([]),
  savingsGoals: z.array(goalSchema).default([]),
  incomeCategories: z.array(categorySchema).default([]),
  expenseCategories: z.array(categorySchema).default([]),
  prefs: prefsSchema.optional(),
});

export async function restoreUserData(input: unknown): Promise<FinanceSnapshot> {
  const userId = await requireUserId();

  // Accept either the wrapped backup file ({ version, data }) or a raw snapshot.
  const raw =
    input && typeof input === "object" && "data" in input
      ? (input as { data: unknown }).data
      : input;
  const data = backupData.parse(raw);

  const categories = [...data.incomeCategories, ...data.expenseCategories];

  await prisma.$transaction([
    // Clear everything owned by this user first…
    prisma.income.deleteMany({ where: { userId } }),
    prisma.expense.deleteMany({ where: { userId } }),
    prisma.savingsGoal.deleteMany({ where: { userId } }),
    prisma.category.deleteMany({ where: { userId } }),
    // …then re-insert from the backup (new ids generated by Prisma defaults).
    prisma.category.createMany({
      data: categories.map((c) => ({
        userId,
        name: c.name,
        icon: c.icon,
        type: c.type as CategoryType,
        isDefault: c.isDefault ?? false,
      })),
      skipDuplicates: true,
    }),
    prisma.income.createMany({
      data: data.incomes.map((i) => ({
        userId,
        date: new Date(i.date),
        source: i.source,
        category: i.category,
        amount: i.amount,
        notes: i.notes ?? null,
      })),
    }),
    prisma.expense.createMany({
      data: data.expenses.map((e) => ({
        userId,
        date: new Date(e.date),
        description: e.description,
        category: e.category,
        amount: e.amount,
        status: e.status,
      })),
    }),
    prisma.savingsGoal.createMany({
      data: data.savingsGoals.map((g) => ({
        userId,
        name: g.name,
        icon: g.icon,
        saved: g.saved,
        target: g.target,
        targetDate: new Date(g.targetDate),
      })),
    }),
    ...(data.prefs
      ? [
          prisma.userPrefs.upsert({
            where: { userId },
            update: data.prefs,
            create: { userId, ...data.prefs },
          }),
        ]
      : []),
  ]);

  return getUserData();
}

export async function resetUserData(): Promise<FinanceSnapshot> {
  const userId = await requireUserId();
  await resetUserToDefaults(userId);
  return getUserData();
}
